### PR TITLE
Add details about plugin development

### PR DESCRIPTION
**Pull request by PhrozenByte**
As promised, albeit later than expected... :laughing: 

I'm not sure whether we should keep the code explanation or not... What do you think? If not, we should basically remove the following part of the paragraph:

> the `PicoDrafts` class (line `3`) hooks into Pico's `onPagesLoaded` event (line `5`), walks through all of Pico's pages (`$pages` parameter; line `7`), searches for pages which filename (`$pageData['id']`) start with a `_` (line `8`) and removes them (line `9`).  To cut a short story even shorter:

Maybe that's a bit "too much" for the about page...

Furthermore the example code IMHO takes a bit too much space... However, I'm not sure how to fix that... The example code is pretty important for a developer to see at first glance how plugins for Pico are created...

Live demo: http://phrozenbyte.github.io/Pico/about/#plugins-extend-picos-php
Traceback: picocms/Pico#352

### CODE REVIEW

**Comment by mayamcdougall** [comment]
Unfortunately, I have to agree with you... this is a bit _much_ for the About page.  Your example is good though, it could easily be used elsewhere!

I like the paragraph on hooking.  It does a good job on its own of explaining why Pico's so easy to write plugins for.

I don't think the code example is too big.  Have you seen the others? :laughing:

Also, if you'd like to keep your code example in, why don't I use it as a screenshot in the "Workflow" gallery? :smiley:

**Comment by mayamcdougall** [comment]
Also, would "triggers" be an okay replacement word for "fires"?  "Fires" just sounds a little odd (not incorrect, just odd).

**Comment by PhrozenByte** [comment]
I've removed the code explanation and replaced "fires" with "triggers".

I don't think moving the code example to the "Workflow" gallery is a good idea, we shouldn't scatter related content all over the page. I was thinking about letting the code example float like the gallery... What do you think about that?

bildschirmfoto am 2016-07-08 um 16 17 28

(Maybe adding a bit more padding to the bottom and right of the code block is a good idea, should make it look less cramped...)

**Comment by mayamcdougall** [comment]
> replaced "fires" with "triggers".

I guess I meant _I'd_ do that during editing if it was an accurate word to use.  It does sound better though. :smile:

> I was thinking about letting the code example float like the gallery

It does look better this way... but I was actually thinking of removing it altogether. :unamused:

Nothing against the example, I'd actually like to use it in its entirety elsewhere in the docs.  I just think that its too much detail for this page.

For comparison, if you look at the themes section, the most I said about Twig is that it's "powerful", and so much so that it "eliminat[es] the need for plugins" (which was your suggestion I believe).

There's no code example, there's no explanation of how Twig works or how simple it is to use.  There's just some links to our Documentation as well as Twig's.

I think the plugins section should be similar to that.  The Hooking paragraph goes into what _I_ think is enough detail about how plugins work.  To someone who knows PHP, I feel like this description of where they can hook into Pico would tell them exactly what they need to know.  At the same time, it won't overwhelm or scare away someone who doesn't know PHP.  :confused:

Also... for the sake of my logic here, I'm not really counting the "Themes" gallery as part of the "Themes" section.  It's there simply because that's the best place to put it, and in my opinion, it serves more as an example of what Pico can look like than of what Twig can do. :stuck_out_tongue_winking_eye:

**Comment by PhrozenByte** [comment]
> It does look better this way... but I was actually thinking of removing it altogether. :unamused:

I know :wink: As I've said, the code example shows the essence of plugin development. IMO it's important to _show_ something that represents plugin development, the same way as screenshots of themes _show_ how themes can look like. Showing Twig example code would not work - Twig is just an fraction of theme development (it's not even the most important part: I know Twig very well, nevertheless I'm no theme developer), not its essence. Theme development is about creating something visual, it's about creativity, yeah, it's even some sort of art - plugin development is about solving problems.

Furthermore, to be honest, Pico primarily addresses people who already know how creating a website works. They aren't scared of some lines of code. Sure, we're trying hard to make Pico newbie-proof and this definitely is an important goal, however, attracting plugin developers is extremely important to make this happen - otherwise Pico wouldn't be able to meet the requirements of all those newbies. A example like this (create a class, add a method, modify a variable - that's it) definitely attracts me as a developer.

However, I'll think about it.

**Comment by mayamcdougall** [comment]
I _knew_ you'd have a counterargument. :wink:

I was too tired last night to say anything useful or that hadn't been said already.  I've made most of my point already. :laughing:

Another point I thought of was that Markdowns and YAML get examples on this page because they are _required_ to know.  If a new user sees those examples and thinks "That's too hard, I just wanted a 'submit' button" then they'll know right away that Pico isn't for them.

But Twig and PHP are more advanced topics. They aren't necessary to _use_ Pico, only to extend it.  You can get by without them.

And I don't mean to make it so black and white. It's not about knowing or not knowing things. I agree with you that it's unlikely a complete web newbie would choose Pico. But, if someone knows a only a little of a subject, I don't want them to feel like they'll have less of an experience with Pico.

If a new user doesn't know PHP (or doesn't know it well enough to matter :wink:), I want them to still "get something" from the Plugins section, and not just skip over it.

Remember where I'm coming from here. I'm the complete opposite perspective as you (though to be honest, we need someone who's more "middle ground" here).  PHP is your bread and butter, you jump at the chance to defend it.  Meanwhile I have to copy and paste an "include" statement, just to be sure I have the syntax right. :laughing:

If you really want this example included, I can see about making it work. I may try to make the explanation a little more "casual" though (which you've mostly already done by removing that section).

Hope this comment isn't really as long as it looks on my phone... It was supposed to be short.  I always have too much to say. :confounded:

**Comment by PhrozenByte** [comment]
Your arguments are completely valid! However, I'm still balancing the pros and cons... In the meantime, just a bit brainstorming:

bildschirmfoto von 2016-07-09 18 31 43

**Comment by mayamcdougall** [comment]
> Your arguments are completely valid

I just add things as I think of them.  They're not supposed to be so long though. :sweat_smile:

I just don't know when to stop writing.

> just a bit brainstorming

I may have done that already... Well... I started it, then reset it when you said that you didn't think the workplace gallery was a good place for it.  (I realize you have it inline here, just explaining why I didn't keep it).

https://github.com/smcdougall/Pico/commit/1b393c77961c3cf6251ff7de97537fa7807eb207

This is a commit that I reset.  I didn't know that GitHub kept them.  I assume they exist somewhere buried in my Git history, since I know that if I specify an ID with `-c`, it remembers the commit message even though I've reset it.

I must have a massive collection of reset commits somewhere. :unamused:

**Comment by PhrozenByte** [comment]
I was thinking about a completely standalone modal, no gallery, nothing - just a regular "Click here" text link. I don't want to integrate it into the workflow gallery, this scatters the content (and it IMHO doesn't belong to the workflow gallery). The alternative is another "standalone" gallery, but that's the same as https://github.com/smcdougall/Pico/pull/3#issuecomment-231372686 in the end (and I still like this solution the most btw, even I didn't make a decision yet). Furthermore, the "image"/modal content is real text, not a image.

**Comment by mayamcdougall** [comment]
> I don't want to integrate it into the workflow gallery

I know, I was just linking the commit for the screenshots I made/discarded, in case we wanted to use it as a standalone image.

> Furthermore, the "image"/modal content is real text, not a image.

Oh... Neat! :smile:

**Comment by mayamcdougall** [comment]
I keep trying to scroll your [image](https://cloud.githubusercontent.com/assets/920356/16690412/12009e9a-4528-11e6-9555-393224d9d6c9.png) from above... :unamused:

Anyway, I agree that if we're keeping this example, this implementation was the best so far.

**Comment by PhrozenByte** [comment]
>  in case we wanted to use it as a standalone image

Sure, but why? Isn't this exactly the same as https://github.com/smcdougall/Pico/pull/3#issuecomment-231372686 :question: :confused:

Maybe we talk at cross purposes the whole time... Do you endorse something like https://github.com/smcdougall/Pico/pull/3#issuecomment-231372686 (or a standalone gallery - what looks quite the same, just a bit smaller)?

**Comment by mayamcdougall** [comment]
> Sure, but why? Isn't this exactly the same as #3 (comment)

Yeah.  I was just sharing.  Also, if you decided you wanted to do the standalone gallery, you could reuse the images I deleted.

---

To clarify though my opinions are ranked like this:
1. Remove the code example and the corresponding paragraph.  Keep the "Hooking" paragraph and the last one.
2. Move the code example and paragraph into a thumbnail/gallery.
3. Shrink the code example into a floating box on the side.
4. The way it is now. :wink:

Ultimately though, we'll do whatever style you like best.

My top choice would still be to put it on another page though. :laughing:

**Comment by PhrozenByte** [comment]
After nearly forgetting about this, I've made a decision. I'll remove the code example altogether, but add a link to a GitHub Gist with the example code. I think this is a good compromise, it's even more separated from the about page as a thumbnail/gallery and doesn't require additional work. I hope this compromise is acceptable for you, I don't want to force you to add something you're _fundamentally_ against (if this is the case please let me know).

btw, I've merged upstream `gh-pages` - because I'm depending on commits of upstream `gh-pages` (namely https://github.com/picocms/Pico/compare/7ebcfede934cf89a62d7653f2eba25b419497254...e1a8764771aa06bb31c4229d9c987da642718a62) :wink: :smiley:

**Comment by mayamcdougall** [comment]
>  I don't want to force you to add something you're fundamentally against

I'm not quite _that_ serious about it. :laughing:

Just trying to keep the page streamlined. :smile:

If you like this solution, it should work fine.  I plan to edit your section anyway, so I'll rework any remaining "rough edges" it may have.

On that note, you've written about the "Drafts" example as if it's a real plugin.  By real, I mean released, supported, published, etc, not just whether or not the example code works.  Do you plan to make it a "real" plugin, or should I clarify that it's just an example?

(Don't worry about fixing it here, as I'll be editing it anyway).

---

Also... I clicked on your Gists page... you play/played Ogame? :laughing:

That game is _SO_ old.  I used to play it in High School.  I think I've had three or four accounts total, some more recent, but all lost to forgetting them in "Vacation Mode" for too long. :unamused:

**Comment by PhrozenByte** [comment]
> If you like this solution, it should work fine. I plan to edit your section anyway, so I'll rework any remaining "rough edges" it may have.

Great! :+1:

> On that note, you've written about the "Drafts" example as if it's a real plugin. By real, I mean released, supported, published, etc, not just whether or not the example code works. Do you plan to make it a "real" plugin, or should I clarify that it's just an example?

I wasn't sure how to phrase it :smile: Yes, please clarify that it's just an example. It's a working example, but not really practical.

---

> you play/played Ogame?

Yeah, I've started playing it again about a year ago or so - after roughly 10 years of absence. I'm playing in the German universe Hyperion, however, it's not very thrilling there, OGame is rather a daily routine of about 20 minutes :smile:

**Comment by mayamcdougall** [comment]
> however, it's not very thrilling there

Lol :laughing:

Yeah, I've always thought it was fun when you first get started.  Building up your colonies and fleet.  Once you get to the point where it takes weeks of resources and/or weeks of research and build time on upgrades, it stops being very interesting.

Especially if you're not a very aggressive player or if everyone else around is out of your league.

Also... "fleetsaving" is just about the worst thing ever.  I can't tell you how many times I've lost all my ships just because I couldn't get online when I thought I'd be able to.

You get home an hour late and find all your ships destroyed...
...and you didn't even get a moon from it! :angry:

**Comment by mayamcdougall** [comment]
Also, it was definitely better _before_ the redesign. :wink:

I'll see about getting this last section finalized either later tonight or more likely tomorrow morning.  With this and cleaning up that last to-do item, we should be ready to merge https://github.com/picocms/Pico/pull/352 very soon. :smile:

**Comment by PhrozenByte** [comment]
> Also, it was definitely better before the redesign. :wink:

https://board.origin.ogame.gameforge.com/index.php/Thread/8761-Retro-server/

> I'll see about getting this last section finalized either later tonight or more likely tomorrow morning. With this and cleaning up that last to-do item, we should be ready to merge picocms#352 very soon. :smile:

Perfect! :+1: :tada:

**Comment by mayamcdougall** [comment]
No thanks, I don't need the extra daily obligation right now. :laughing:

I saw your script was for the retro server, so I had to comment. :wink:

Also, as slow and bloated as the redesign was (especially when it first came out), the original hasn't exactly aged well either.

Still, you've got to miss the days of "browser games", before flash games and mobile games killed them off.

Maybe we missed our calling by a few years :stuck_out_tongue_winking_eye:

Time to build a browser game out of Pico. :smile:

Though, I think "flat file" user accounts might not be the right approach...

**Pull request merged**
