### PR TITLE
Portfolio: Fix details view animation

### PR DESCRIPTION
**Pull request by PhrozenByte**
This has been written by someone who definitely had no idea what he's doing... What a mess...

picocms/Pico#358

### CODE REVIEW

**Comment by mayamcdougall** [comment]
Nice work on fixing that CPU usage.  It also feels a lot smoother now, probably because it was lagging more than I realized before. :+1:

I did find one bug though... :sweat:

If the fullsize image isn't already loaded/cached, the size of the content area is calculated wrong.  Instead of fitting the image, it fits to the text, which results in the image being cut off on an item with shorter text.

After the image is loaded or if it is in the browser cache, it functions properly from then onward.  Unfortunately, this happens for every item, as the images are loaded on demand.  It results in a very broken first visit to the page.

This may also be a result of my slower connection at work, but either way needs to be fixed.

Here's a screenshot of the issue (complete with Network Panel :smile:)
image

If I were to revert this merge, does it return to its "Ready to Merge" status?  Or will you have to submit a new PR?

**Comment by PhrozenByte** [comment]
I'll open a new PR.

**Comment by mayamcdougall** [comment]
So that's a "No"? :unamused:

Guess I should have tested it first. :sweat_smile:

**Comment by PhrozenByte** [comment]
What do you mean by "Ready to Merge" status?

**Comment by mayamcdougall** [comment]
If I click "Revert", does it go back to how it was, letting me choose to merge it again later on, or does it get rejected/closed?

**Comment by PhrozenByte** [comment]
No, it adds another commit reverting the merge and keeps the PR closed. You can't reopen a PR once it has been merged. As said, I'll open a new PR.

**Comment by mayamcdougall** [comment]
> and keeps the PR closed. You can't reopen a PR once it has been merged.

Okay, that's what I was wondering. :disappointed:

**Pull request merged**
