### PR TITLE
Finalize Portfolio

### PR DESCRIPTION
**Pull request by PhrozenByte**
Really, this looks like more than it actually is :smile: The first commit just changes indentation and moves the duplicate code into `capture` blocks, so I actually didn't change anything, but GitHub recognizes it as new code :wink: You did a great job! :+1: There wasn't much to do.

So, what did I actually change... As said, I've moved duplicate code into `capture` blocks. The button text now defaults to "Download" and I've removed both `include.defaultThumbnail` (unused) and `item.description` (you're already using `item.content`). The meta data is now aligned to the content (the only visible change). The original layout is now called `jumbovision` (like those gigantic televisions), the "columns" layout is called `card` (like business cards). You can change the layout on a per-item or per-portfolio basis (`pico_edit` currently uses the `card` layout; what do you think about that?). There's now a `defaultImage` option with which you can overwrite what image is being shown when the item doesn't specify any images (like most plugins). There's no fancybox popup for `defaultImage` on purpose. And the stylesheet is now responsive and works with IE 9+. IE 8 is broken for some reason - and I've absolutely no idea why... I'll do more research...

Live Demo: http://phrozenbyte.github.io/Pico/plugins/
Backreference: picocms/Pico#358

### CODE REVIEW

**Comment by mayamcdougall** [comment]
> jumbovision

:laughing: :+1:

So, as usual, I noted an odd, hard to reproduce bug.  Probably so small it can be overlooked.  ~~I couldn't even get it to occur predictably.~~  Actually, upon further investigation it wasn't your changes, since it happens in my version.

If you accidentally double-click on a thumbnail, the content area stays open, but the page layout goes back to normal.  Also, the content area's image will revert back to its full size while the content area is closing in this broken state.  This part is likely due to a CSS class disappearing at an unplanned point.  The image thing was actually what caused me to notice it though.

This bug probably came from something in #4 / #5.\*  While it doesn't occur in the [original implementation](http://themes.iki-bir.com/webpaint/multipage/full/portfolio.html#), I was able to make parts of their page disappear completely with some double-clicking hijinks.

*~~(There was a small section of Javascript I commented out before though.  I'll make sure it didn't have anything to do with this.)~~ Edit: Nevermind, I see you removed that section anyway.

Ours only seems to be a visual bug.  It fixes itself the next time you open or close the content area.  Their original implementation broke so much that it required a page refresh to fix. :laughing:

Anyway... just wanted to point that out.  It's probably not worth fixing unless it's like a five second fix.

Back on topic, I'll look through your changes soon, but what you've described sounds good. :+1:

**Comment by mayamcdougall** [comment]
> test test test test
> lol, you're never satisfied. :wink:

**Comment by PhrozenByte** [comment]
> > test test test test
> 
> lol, you're never satisfied. :wink:

We're ready to roll... I did some kind of a "rage code refactoring" :laughing:

With the previous mess of a code it was nearly impossible to track any bugs down (unused code, conflicting code, duplicate code...), this shouldn't be a problem anymore. Works fine with IE8+ and on mobile devices (what btw wasn't the case before, just try it yourself, open the Webpaint demo page with a mobile browser and scroll up so that the navigation bar appears - what a great UX :laughing:).

This is still far away from being perfect, normally I wouldn't use jQuery for this (I've to due to Isotope), because jQuery fucks up the stylesheet pretty much and makes it impossible to actually recover the original/"clean" state (what is a prerequisite to e.g. support aborting the close animation). So if you want to open another item, the previous item is first fully closed (and user interaction is ignored in the meantime) before actually opening the new item.

There are still some (now much more rare!) circumstances under which you can fuck up everything, but as far as I know all these states can be recovered by opening another item...

**#edit:** btw, one of the reasons why I've done this now is because I made the decision that we'll keep Isotope when switching from Jekyll to Pico for picocms.org. I'm planning to do a code refactoring anyway, so I actually just did this earlier than planned.

**Comment by mayamcdougall** [comment]
:+1:

I've found one new bug though, but I have _no_ idea what is causing it.  In "Opera Mobile", the mobile layout isn't triggering properly anymore.  I've also tried the mobile versions of both Firefox and Chrome, and they work fine.

For whatever reason, the mobile layout is only partially triggering.  The background colors on the header and footer are shrunken (and likely their entire elements), but the rest of the layout isn't rearranging.

This could just be a bug in Opera.  It's built on a slightly older version of Chromium.  But still, it worked before, and still works correctly on my version of the site.

screenshot_20160918-190038

screenshot_20160918-190047

**Comment by PhrozenByte** [comment]
*shrug*

Does this happen on all pages or just on the plugins/themes page? I'm btw unable to reproduce this in my Android virtual machine with Opera... Or is this Opera Mini (crashes all the time)?

**Comment by mayamcdougall** [comment]
It was happening on all the pages, and on Opera Mobile, not Mini.

I have no idea what's causing it for me.  I backed up and wiped my Opera browser's data and it works fine now (even once I restored my data).

Must have been some weird cache issue or something.  :sweat_smile:

It's hard to figure that out on mobile. :unamused:

**Comment by PhrozenByte** [comment]
> It's hard to figure that out on mobile. :unamused:

Depends. Chrome, Firefox and Opera all provide remote debugging techniques which we could use if there's an issue. Anyway, they seem to work (and it's quite unusual that mobile doesn't work when their desktop-counterparts work). The only browsers which don't work are Dolphin and UC Browser (with Dolphin you can open and close the detail view at least once, UC Browser doesn't work at all). However, neither Dolphin nor UC Browser provide any debugging technique, so it's impossible for us to figure out what's going on. And they don't have a considerable market share anyway... So... Who cares :laughing:

**Comment by mayamcdougall** [comment]
No, we only care about _real_ browsers. :wink:

.... which is why I'm always negligent of IE. :laughing:

I know they have remote debugging options, but, for example, there's no simple way to hard reload a page.  I probably should have tried clearing the cache, etc, before I commented.  I just really didn't think I'd have anything cached for _your_ github.io in that browser to worry about.

Also, since the big-name mobile browsers typically run on the same engine as their desktop counterparts, I'd usually just use their desktop-based responsive design views.  This issue was occurring only on that browser install though. :confounded:

**Comment by mayamcdougall** [comment]
:open_mouth: 

That's an impressive amount of JavaScript refactoring.  (Not that I've tried to understand any of it. :unamused: )

So I've finally finished reading through the changes (the regular ones).  Looks a lot cleaner than before. :+1: 

Now to make that thumbnail image so they aren't all using the screenshot of the default theme. :laughing:

Any last minute changes / decisions? Or should I go ahead and merge it?

**Comment by PhrozenByte** [comment]
> That's an impressive amount of JavaScript refactoring.

_Rage_ refactoring :laughing: 

> Any last minute changes / decisions? Or should I go ahead and merge it?

Nope, go ahead :smiley: :+1:

**Pull request merged**
